MCU_SERIES = MIMXRT1064
MCU_VARIANT = MIMXRT1064DVL6A

MICROPY_FLOAT_IMPL = double
MICROPY_PY_LWIP = 1
MICROPY_PY_USSL = 1
MICROPY_SSL_MBEDTLS = 1

CFLAGS += -DFSL_FEATURE_PHYKSZ8081_USE_RMII50M_MODE=1

SRC_ETH_C = \
	hal/phy/device/phyksz8081/fsl_phyksz8081.c \

CFLAGS += -DBOARD_FLASH_SIZE=0x400000

JLINK_PATH ?= /media/RT1064-EVK/

deploy: $(BUILD)/firmware.bin
	cp $< $(JLINK_PATH)
