MCU_SERIES = MIMXRT1064
MCU_VARIANT = MIMXRT1064DVL6A

MICROPY_FLOAT_IMPL = double

BOARD_FLASH_TYPE ?= hyperflash
BOARD_FLASH_SIZE ?= 0x4000000  # 64MB

CFLAGS += -DCPU_HEADER_H='<$(MCU_SERIES).h>' \
			-DCFG_TUSB_MCU=OPT_MCU_MIMXRT10XX

JLINK_PATH ?= /media/RT1064-EVK/

deploy: $(BUILD)/firmware.bin
	cp $< $(JLINK_PATH)
