MCU_SERIES = SAMD21
CMSIS_MCU = SAMD21E18A
LD_FILES = boards/samd21x18a.ld sections.ld
TEXT0 = 0x2000

ifeq ($(BOARD_VARIANT), SPIFLASH)
	CFLAGS += -DMICROPY_HW_SPIFLASH=1
	MICROPY_HW_CODESIZE ?= 248K
endif