MCU_SERIES = MIMXRT1052
MCU_VARIANT = MIMXRT1052DVL6B

JLINK_PATH ?= /media/RT1050-EVK/

MICROPY_FLOAT_IMPL = double
MICROPY_PY_LWIP = 1
MICROPY_PY_USSL = 1
MICROPY_SSL_MBEDTLS = 1

CFLAGS += -DFSL_FEATURE_PHYKSZ8081_USE_RMII50M_MODE=1

SRC_ETH_C = \
	hal/phy/device/phyksz8081/fsl_phyksz8081.c \

deploy: $(BUILD)/firmware.bin
	cp $< $(JLINK_PATH)
