MCU_SERIES = MIMXRT1052
MCU_VARIANT = MIMXRT1052DVL6B

MICROPY_FLOAT_IMPL = double

BOARD_FLASH_TYPE ?= hyperflash
BOARD_FLASH_SIZE ?= 0x4000000  # 64MB

CFLAGS += -DCPU_HEADER_H='<$(MCU_SERIES).h>' \
			-DCFG_TUSB_MCU=OPT_MCU_MIMXRT10XX

JLINK_PATH ?= /media/RT1050-EVKB/

deploy: $(BUILD)/firmware.bin
	cp $< $(JLINK_PATH)
