MCU_SERIES = MIMXRT1062
MCU_VARIANT = MIMXRT1062DVJ6A

MICROPY_FLOAT_IMPL = double
MICROPY_PY_LWIP = 1
MICROPY_PY_USSL = 1
MICROPY_SSL_MBEDTLS = 1

CFLAGS += -DFSL_FEATURE_PHYKSZ8081_USE_RMII50M_MODE=1

SRC_ETH_C = \
	hal/phy/device/phyksz8081/fsl_phyksz8081.c \

JLINK_PATH ?= /media/RT1060-EVK/
JLINK_COMMANDER_SCRIPT = $(BUILD)/script.jlink

ifdef JLINK_IP
JLINK_CONNECTION_SETTINGS = -IP $(JLINK_IP)
else
JLINK_CONNECTION_SETTINGS = -USB
endif

deploy: $(BUILD)/firmware.bin
	cp $< $(JLINK_PATH)
