MCU_SERIES = MIMXRT1176
MCU_VARIANT = MIMXRT1176DVL6B

MICROPY_FLOAT_IMPL = double

BOARD_FLASH_TYPE ?= qspi_nor
BOARD_FLASH_SIZE ?= 0x1000000  # 16MB

JLINK_PATH ?= /media/RT1170-EVKB/

deploy: $(BUILD)/firmware.bin
	cp $< $(JLINK_PATH)
