MCU_SERIES = MIMXRT1176
MCU_VARIANT = MIMXRT1176DVMAA
MCU_CORE = _cm7

MICROPY_FLOAT_IMPL = double
MICROPY_PY_MACHINE_SDCARD = 1
MICROPY_HW_FLASH_TYPE ?= qspi_nor
MICROPY_HW_FLASH_SIZE ?= 0x1000000  # 16MB

MICROPY_HW_SDRAM_AVAIL = 1
MICROPY_HW_SDRAM_SIZE  = 0x4000000  # 64MB

CFLAGS += -DCPU_MIMXRT1176DVMAA_cm7 \
		-DCPU_HEADER_H='<$(MCU_SERIES)$(MCU_CORE).h>'
