MCU_SERIES = MIMXRT1176
MCU_VARIANT = MIMXRT1176DVL6B

MICROPY_FLOAT_IMPL = double

BOARD_FLASH_TYPE ?= qspi_nor
BOARD_FLASH_SIZE ?= 0x1000000  # 16MB

CFLAGS += -DCPU_MIMXRT1176AVM8A_cm7 \
			-DCPU_HEADER_H='<$(MCU_SERIES)_cm7.h>'

INC += -I$(TOP)/$(MCU_DIR)/drivers/cm7

JLINK_PATH ?= /media/RT1170-EVKB/

deploy: $(BUILD)/firmware.bin
	cp $< $(JLINK_PATH)
