freeze("$(PORT_DIR)/scripts")
freeze("$(MPY_DIR)/tools", ("upip.py", "upip_utarfile.py"))
freeze('$(MPY_DIR)/../pye', 'pye.py')
freeze("$(MPY_DIR)/../upysh", "upysh.py")
include("$(MPY_DIR)/extmod/uasyncio/manifest.py")
include("$(MPY_DIR)/drivers/neopixel/manifest.py")
